POST http://localhost:3002/historicplayers
Content-Type: application/json

{
  "name": "florencia vicente",
  "position": "defender",
  "nationality": "Argentinian",
  "region": "America"
}

#####

PUT http://localhost:3002/historicplayers/68704c622e822d153842da01
Content-Type: application/json

{
  "name": "ruberto",
  "position": "Forward",
  "nationality": "croatian",
  "region": "europe"
}

######
PATCH http://localhost:3002/historicplayers/68704c622e822d153842da01
Content-Type: application/json

{
  "name": "JAVIER"
}
#####
DELETE http://localhost:3002/historicplayers/68704c622e822d153842da01
#####
DELETE http://localhost:3002/historicplayers/likskdjdoinundfiwbibfi
#####
POST http://localhost:3002/api/register
Content-Type: application/json

{
  "username": "lautaro2",
  "email": "lautaro2@example.com",
  "password": "123456"
}

######
POST  http://localhost:3002/api/login
Content-Type: application/json

{
  "email": "lautaro@example.com",
  "password": "123456"
}

######
GET http://localhost:3002/api/profile



