POST http://localhost:3002/historicplayers
Content-Type: application/json

{
  "name": "florencia vicente",
  "position": "defender",
  "nationality": "Argentinian",
  "region": "America"
}

#####

PUT http://localhost:3002/historicplayers/68704c622e822d153842da01
Content-Type: application/json

{
  "name": "ruberto",
  "position": "Forward",
  "nationality": "croatian",
  "region": "europe"
}

######
PATCH http://localhost:3002/historicplayers/68704c622e822d153842da01
Content-Type: application/json

{
  "name": "JAVIER"
}
#####
DELETE http://localhost:3002/historicplayers/1616161616
#####
DELETE http://localhost:3002/historicplayers/likskdjdoinundfiwbibfi
#####

POST http://localhost:3002/api/register
Content-Type: application/json

{
  "username": "lautaro",
  "email": "lautarolezcano@gmail.com",
  "password": "123456"
}


######
POST  http://localhost:3002/api/login
Content-Type: application/json

{
  "email": "lauta@example.com",
  "password": "123456"
}

######
GET http://localhost:3002/api/profile
Cookie: user-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4N2QzZGNmYzlmYzM4MWQwZGJiNDcwZCIsIm5hbWUiOiJsYXV0YSIsImVtYWlsIjoibGF1dGFAZXhhbXBsZS5jb20iLCJ0eXBlIjoidXNlciIsImlhdCI6MTc1MzEzMzQ4NywiZXhwIjoxNzUzMTQwNjg3fQ.hucijnRjzmfXfZj4f3hDCZMc1NbNi460MnO_tcwKAdE



